# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

common: &common
  adapter: postgresql
  pool: 5
  encoding: unicode
  username: railstutorial
  password: railstutorial # from psql setup, see Postgresql

development:
  <<: *common
  database: railstutorial_development

test:
  <<: *common
  database: railstutorial_test

production:
  <<: *common
  database: railstutorial_production
